Техническое задание № 13, add-controllers
voland1711/java-shareit pull request #1
Opened 2023-03-01 21:17 UTC by voland1711

2023-03-01 21:31 UTC, voland1711 reviewed
Внес исправления в соответствии с CodeStyle

2023-03-01 21:36 UTC, voland1711 reviewed
Внес дополнительные исправления, в соответствии с CodeStyle

2023-03-01 22:07 UTC, voland1711 reviewed
Исправление тест.

2023-03-02 08:30 UTC, voland1711 reviewed
Внёс исправления

2023-03-03 06:06 UTC, Frilock requested changes
Добрый день, оставил ряд небольших комментариев к работе, жду новую версию

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> getAllItems(@RequestHeader("X-Sharer-User-Id") long userId) {
Литерал X-Sharer-User-Id повторяется более трех раз - вынесите его в константное поле класса

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Предлагаю входное значение пометить аннотацией Nonnull от jetbrains, чтобы было понятно сразу, что вы гарантируете что данный метод не может принимать null поле

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getDescription().toLowerCase().contains(text))
Можно воспользоваться StringUtils.containsIgnoreCase

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private void existItem(long userId) {
Предлагаю добавить existItemById

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName() == null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isEmpty()) {
Лучше StringUtils.isBlack

2023-03-03 06:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final Map<Long, User> users = new HashMap<>();
А зачем 3 коллекции? По моему с помощью stream.filter из одной сможете получить остальные 2

2023-03-06 05:59 UTC, Frilock approved these changes
Принял, но есть 2 мелких комментария

2023-03-06 05:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String sharerUserId = "X-Sharer-User-Id";
Когда у Вас константное поле - static final, то именуется оно не через camelCase, а вот так SHARER_USER_ID

2023-03-06 05:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +    public static ItemDto toItemDto(@NonNull Item item) {
К другим методам мапперов это тоже относится. Смысл в том, чтобы показать что тут NPE был не может

2023-03-13 18:21 UTC, merged