Add docker
voland1711/java-shareit pull request #4
Opened 2023-05-25 19:02 UTC by voland1711

2023-05-26 20:18 UTC, Frilock requested changes
Добрый вечер, тесты удалять в приложении не нужно, адаптируйте их под текущую реализацию. Тесты валидации перенесите в gateway. Кроме того, попросил Вас сделать в основном pom файле блок dependencyManager, и зависимости для которых вы указываете версию, перенести туда.

2023-05-26 20:18 UTC, Frilock commented on server/pom.xml
> +		<commons-lang.version>2.6</commons-lang.version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии.

2023-05-26 20:18 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/ErrorHandler.java
> +//    @ExceptionHandler
Закомментированного кода быть в приложении не должно

2023-05-26 20:18 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                               @RequestParam(name = "state",defaultValue = "ALL") String stateParam,
после запятой нужен пробел

2023-05-28 09:15 UTC, Frilock approved these changes
Принято, но есть нюансы, первое - добавление подозрительной библиотеки, без которой можно спокойно обойтись. Второе, зачем создаете пустые конструкторы в тестовых классах?

2023-05-28 09:15 UTC, Frilock commented on gateway/pom.xml
> +            <version>0.0.20131108.vaadin1</version>
Во первых зачем вам эта библиотека? В данной работе можно спокойно обойтись без нее
Во вторых, вы вроде сделали блок dependencyManager, так почему библиотеку эту туда не добавляете?

2023-05-28 09:15 UTC, Frilock commented on gateway/src/test/java/ru/practicum/shareit/booking/dto/BookingShortDtoTest.java
> +    BookingShortDtoTest() throws JSONException {
Зачем тут пустой конструктор?

2023-05-28 11:00 UTC, voland1711 commented on gateway/pom.xml
> +            <version>0.0.20131108.vaadin1</version>
Честно говоря, сам не понял как она попала сюда. Видимо добавил случайно.

2023-05-28 15:51 UTC, merged